// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb21tb24ucHJvdG8SBXByb3RvIicKC0Jhc2VSZXF1ZXN0EhgKAmlkGAEg",
            "ASgOMgwucHJvdG8uQXBpSWQiWgoMQmFzZVJlc3BvbnNlEh8KBGNvZGUYASAB",
            "KA4yES5wcm90by5TdGF0dXNDb2RlEhgKAmlkGAIgASgOMgwucHJvdG8uQXBp",
            "SWQSDwoHbWVzc2FnZRgDIAEoCSIxCg1Db21tb25SZXF1ZXN0EiAKBGJhc2UY",
            "ASABKAsyEi5wcm90by5CYXNlUmVxdWVzdCIzCg5Db21tb25SZXNwb25zZRIh",
            "CgRiYXNlGAEgASgLMhMucHJvdG8uQmFzZVJlc3BvbnNlKtwCCgpTdGF0dXND",
            "b2RlEhIKDlNUQVRVU19VTktOT1dOEAASEwoOU1RBVFVTX1NVQ0NFU1MQyAES",
            "FwoSU1RBVFVTX0JBRF9SRVFVRVNUEJADEhgKE1NUQVRVU19VTkFVVEhPUkla",
            "RUQQkQMSFQoQU1RBVFVTX0ZPUkJJRERFThCTAxIVChBTVEFUVVNfTk9UX0ZP",
            "VU5EEJQDEhoKFVNUQVRVU19JTlRFUk5BTF9FUlJPUhD0AxIaChVTVEFUVVNf",
            "SU5WQUxJRF9QQVJBTVMQ6QcSGgoVU1RBVFVTX1VTRVJfTk9UX0VYSVNUEOoH",
            "Eh4KGVNUQVRVU19VU0VSX0FMUkVBRFlfRVhJU1QQ6wcSGgoVU1RBVFVTX1BB",
            "U1NXT1JEX0VSUk9SEOwHEhkKFFNUQVRVU19UT0tFTl9JTlZBTElEEO0HEhkK",
            "FFNUQVRVU19UT0tFTl9FWFBJUkVEEO4HKsgECgVBcGlJZBIPCgtBUElfVU5L",
            "Tk9XThAAEhUKEEFQSV9SRUdJU1RFUl9SRVEQ6QcSFgoRQVBJX1JFR0lTVEVS",
            "X1JFU1AQ6gcSEgoNQVBJX0xPR0lOX1JFURDrBxITCg5BUElfTE9HSU5fUkVT",
            "UBDsBxITCg5BUElfTE9HT1VUX1JFURDtBxIUCg9BUElfTE9HT1VUX1JFU1AQ",
            "7gcSGgoVQVBJX0dFVF9IRVJPX0lORk9fUkVRENEPEhsKFkFQSV9HRVRfSEVS",
            "T19JTkZPX1JFU1AQ0g8SGQoUQVBJX1NFVF9VU0VfSEVST19SRVEQ0w8SGgoV",
            "QVBJX1NFVF9VU0VfSEVST19SRVNQENQPEhIKDUFQSV9NQVRDSF9SRVEQuRcS",
            "EwoOQVBJX01BVENIX1JFU1AQuhcSGwoWQVBJX01BVENIX1NVQ0NFU1NfUkVT",
            "UBC7FxIZChRBUElfQkFUVExFX1JFQURZX1JFURC8FxIaChVBUElfQkFUVExF",
            "X1JFQURZX1JFU1AQvRcSHgoZQVBJX0JBVFRMRV9DT1VOVERPV05fUkVTUBC+",
            "FxIaChVBUElfQkFUVExFX1NUQVJUX1JFU1AQvxcSFwoSQVBJX0ZSQU1FX1NZ",
            "TkNfUkVREMAXEhgKE0FQSV9GUkFNRV9TWU5DX1JFU1AQwRcSGQoUQVBJX0NB",
            "TkNFTF9NQVRDSF9SRVEQwhcSGgoVQVBJX0NBTkNFTF9NQVRDSF9SRVNQEMMX",
            "EhgKE0FQSV9GUkFNRV9EQVRBX1JFU1AQxBdCCVoHLi9wcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.StatusCode), typeof(global::Proto.ApiId), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.BaseRequest), global::Proto.BaseRequest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.BaseResponse), global::Proto.BaseResponse.Parser, new[]{ "Code", "Id", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.CommonRequest), global::Proto.CommonRequest.Parser, new[]{ "Base" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.CommonResponse), global::Proto.CommonResponse.Parser, new[]{ "Base" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 状态码枚举
  /// </summary>
  public enum StatusCode {
    /// <summary>
    /// 未知状态
    /// </summary>
    [pbr::OriginalName("STATUS_UNKNOWN")] StatusUnknown = 0,
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("STATUS_SUCCESS")] StatusSuccess = 200,
    /// <summary>
    /// 请求错误
    /// </summary>
    [pbr::OriginalName("STATUS_BAD_REQUEST")] StatusBadRequest = 400,
    /// <summary>
    /// 未授权
    /// </summary>
    [pbr::OriginalName("STATUS_UNAUTHORIZED")] StatusUnauthorized = 401,
    /// <summary>
    /// 禁止访问
    /// </summary>
    [pbr::OriginalName("STATUS_FORBIDDEN")] StatusForbidden = 403,
    /// <summary>
    /// 未找到
    /// </summary>
    [pbr::OriginalName("STATUS_NOT_FOUND")] StatusNotFound = 404,
    /// <summary>
    /// 服务器内部错误
    /// </summary>
    [pbr::OriginalName("STATUS_INTERNAL_ERROR")] StatusInternalError = 500,
    /// <summary>
    /// 业务状态码 (1000+)
    /// </summary>
    [pbr::OriginalName("STATUS_INVALID_PARAMS")] StatusInvalidParams = 1001,
    /// <summary>
    /// 用户不存在
    /// </summary>
    [pbr::OriginalName("STATUS_USER_NOT_EXIST")] StatusUserNotExist = 1002,
    /// <summary>
    /// 用户已存在
    /// </summary>
    [pbr::OriginalName("STATUS_USER_ALREADY_EXIST")] StatusUserAlreadyExist = 1003,
    /// <summary>
    /// 密码错误
    /// </summary>
    [pbr::OriginalName("STATUS_PASSWORD_ERROR")] StatusPasswordError = 1004,
    /// <summary>
    /// Token无效
    /// </summary>
    [pbr::OriginalName("STATUS_TOKEN_INVALID")] StatusTokenInvalid = 1005,
    /// <summary>
    /// Token过期
    /// </summary>
    [pbr::OriginalName("STATUS_TOKEN_EXPIRED")] StatusTokenExpired = 1006,
  }

  /// <summary>
  /// 接口ID枚举
  /// </summary>
  public enum ApiId {
    [pbr::OriginalName("API_UNKNOWN")] ApiUnknown = 0,
    /// <summary>
    /// 认证相关接口 (1000+)
    /// 注册相关
    /// </summary>
    [pbr::OriginalName("API_REGISTER_REQ")] ApiRegisterReq = 1001,
    /// <summary>
    /// 注册响应
    /// </summary>
    [pbr::OriginalName("API_REGISTER_RESP")] ApiRegisterResp = 1002,
    /// <summary>
    /// 登录相关
    /// </summary>
    [pbr::OriginalName("API_LOGIN_REQ")] ApiLoginReq = 1003,
    /// <summary>
    /// 登录响应
    /// </summary>
    [pbr::OriginalName("API_LOGIN_RESP")] ApiLoginResp = 1004,
    /// <summary>
    /// 登出相关
    /// </summary>
    [pbr::OriginalName("API_LOGOUT_REQ")] ApiLogoutReq = 1005,
    /// <summary>
    /// 登出响应
    /// </summary>
    [pbr::OriginalName("API_LOGOUT_RESP")] ApiLogoutResp = 1006,
    /// <summary>
    /// 英雄相关接口 (2000+)
    /// 获取英雄信息
    /// </summary>
    [pbr::OriginalName("API_GET_HERO_INFO_REQ")] ApiGetHeroInfoReq = 2001,
    /// <summary>
    /// 获取英雄信息响应
    /// </summary>
    [pbr::OriginalName("API_GET_HERO_INFO_RESP")] ApiGetHeroInfoResp = 2002,
    /// <summary>
    /// 设置使用英雄
    /// </summary>
    [pbr::OriginalName("API_SET_USE_HERO_REQ")] ApiSetUseHeroReq = 2003,
    /// <summary>
    /// 设置使用英雄响应
    /// </summary>
    [pbr::OriginalName("API_SET_USE_HERO_RESP")] ApiSetUseHeroResp = 2004,
    /// <summary>
    /// 战斗相关接口 (3000+)
    /// 匹配相关
    /// </summary>
    [pbr::OriginalName("API_MATCH_REQ")] ApiMatchReq = 3001,
    /// <summary>
    /// 匹配响应
    /// </summary>
    [pbr::OriginalName("API_MATCH_RESP")] ApiMatchResp = 3002,
    /// <summary>
    /// 匹配成功响应
    /// </summary>
    [pbr::OriginalName("API_MATCH_SUCCESS_RESP")] ApiMatchSuccessResp = 3003,
    /// <summary>
    /// 战斗准备
    /// </summary>
    [pbr::OriginalName("API_BATTLE_READY_REQ")] ApiBattleReadyReq = 3004,
    /// <summary>
    /// 战斗准备响应
    /// </summary>
    [pbr::OriginalName("API_BATTLE_READY_RESP")] ApiBattleReadyResp = 3005,
    /// <summary>
    /// 战斗开始
    /// </summary>
    [pbr::OriginalName("API_BATTLE_COUNTDOWN_RESP")] ApiBattleCountdownResp = 3006,
    /// <summary>
    /// 战斗开始响应
    /// </summary>
    [pbr::OriginalName("API_BATTLE_START_RESP")] ApiBattleStartResp = 3007,
    /// <summary>
    /// 帧同步
    /// </summary>
    [pbr::OriginalName("API_FRAME_SYNC_REQ")] ApiFrameSyncReq = 3008,
    /// <summary>
    /// 帧同步响应
    /// </summary>
    [pbr::OriginalName("API_FRAME_SYNC_RESP")] ApiFrameSyncResp = 3009,
    /// <summary>
    /// 取消匹配
    /// </summary>
    [pbr::OriginalName("API_CANCEL_MATCH_REQ")] ApiCancelMatchReq = 3010,
    /// <summary>
    /// 取消匹配响应
    /// </summary>
    [pbr::OriginalName("API_CANCEL_MATCH_RESP")] ApiCancelMatchResp = 3011,
    /// <summary>
    /// 战斗帧数据
    /// </summary>
    [pbr::OriginalName("API_FRAME_DATA_RESP")] ApiFrameDataResp = 3012,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 基础请求对象 - 所有请求都应该基于此对象
  /// </summary>
  public sealed partial class BaseRequest : pb::IMessage<BaseRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseRequest> _parser = new pb::MessageParser<BaseRequest>(() => new BaseRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseRequest(BaseRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseRequest Clone() {
      return new BaseRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Proto.ApiId id_ = global::Proto.ApiId.ApiUnknown;
    /// <summary>
    /// 接口ID，标识是哪个接口
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ApiId Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != global::Proto.ApiId.ApiUnknown) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != global::Proto.ApiId.ApiUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != global::Proto.ApiId.ApiUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != global::Proto.ApiId.ApiUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id != global::Proto.ApiId.ApiUnknown) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = (global::Proto.ApiId) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = (global::Proto.ApiId) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 基础响应对象 - 所有响应都应该基于此对象
  /// </summary>
  public sealed partial class BaseResponse : pb::IMessage<BaseResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseResponse> _parser = new pb::MessageParser<BaseResponse>(() => new BaseResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseResponse(BaseResponse other) : this() {
      code_ = other.code_;
      id_ = other.id_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseResponse Clone() {
      return new BaseResponse(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Proto.StatusCode code_ = global::Proto.StatusCode.StatusUnknown;
    /// <summary>
    /// 本次请求的状态码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.StatusCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private global::Proto.ApiId id_ = global::Proto.ApiId.ApiUnknown;
    /// <summary>
    /// 接口ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ApiId Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    /// <summary>
    /// 响应消息（可选）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Id != other.Id) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::Proto.StatusCode.StatusUnknown) hash ^= Code.GetHashCode();
      if (Id != global::Proto.ApiId.ApiUnknown) hash ^= Id.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != global::Proto.StatusCode.StatusUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Id != global::Proto.ApiId.ApiUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Id);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != global::Proto.StatusCode.StatusUnknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Id != global::Proto.ApiId.ApiUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Id);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::Proto.StatusCode.StatusUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Id != global::Proto.ApiId.ApiUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseResponse other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::Proto.StatusCode.StatusUnknown) {
        Code = other.Code;
      }
      if (other.Id != global::Proto.ApiId.ApiUnknown) {
        Id = other.Id;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::Proto.StatusCode) input.ReadEnum();
            break;
          }
          case 16: {
            Id = (global::Proto.ApiId) input.ReadEnum();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = (global::Proto.StatusCode) input.ReadEnum();
            break;
          }
          case 16: {
            Id = (global::Proto.ApiId) input.ReadEnum();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CommonRequest : pb::IMessage<CommonRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CommonRequest> _parser = new pb::MessageParser<CommonRequest>(() => new CommonRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CommonRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonRequest(CommonRequest other) : this() {
      base_ = other.base_ != null ? other.base_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonRequest Clone() {
      return new CommonRequest(this);
    }

    /// <summary>Field number for the "base" field.</summary>
    public const int BaseFieldNumber = 1;
    private global::Proto.BaseRequest base_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.BaseRequest Base {
      get { return base_; }
      set {
        base_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CommonRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CommonRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Base, other.Base)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (base_ != null) hash ^= Base.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (base_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Base);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (base_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Base);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (base_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Base);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CommonRequest other) {
      if (other == null) {
        return;
      }
      if (other.base_ != null) {
        if (base_ == null) {
          Base = new global::Proto.BaseRequest();
        }
        Base.MergeFrom(other.Base);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (base_ == null) {
              Base = new global::Proto.BaseRequest();
            }
            input.ReadMessage(Base);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (base_ == null) {
              Base = new global::Proto.BaseRequest();
            }
            input.ReadMessage(Base);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CommonResponse : pb::IMessage<CommonResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CommonResponse> _parser = new pb::MessageParser<CommonResponse>(() => new CommonResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CommonResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonResponse(CommonResponse other) : this() {
      base_ = other.base_ != null ? other.base_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommonResponse Clone() {
      return new CommonResponse(this);
    }

    /// <summary>Field number for the "base" field.</summary>
    public const int BaseFieldNumber = 1;
    private global::Proto.BaseResponse base_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.BaseResponse Base {
      get { return base_; }
      set {
        base_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CommonResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CommonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Base, other.Base)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (base_ != null) hash ^= Base.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (base_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Base);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (base_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Base);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (base_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Base);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CommonResponse other) {
      if (other == null) {
        return;
      }
      if (other.base_ != null) {
        if (base_ == null) {
          Base = new global::Proto.BaseResponse();
        }
        Base.MergeFrom(other.Base);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (base_ == null) {
              Base = new global::Proto.BaseResponse();
            }
            input.ReadMessage(Base);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (base_ == null) {
              Base = new global::Proto.BaseResponse();
            }
            input.ReadMessage(Base);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
